<?php

namespace Database\Seeders;

use App\Models\News;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class NewsSeeder extends Seeder
{
    /**
     * Seed SEO-focused public news articles.
     */
    public function run(): void
    {
        $articles = [
            [
                'title' => '10 Tips Internet Stabil di Rumah agar Video Call, Game, dan Streaming Tetap Lancar',
                'excerpt' => 'Panduan praktis membuat koneksi internet rumah lebih stabil, mulai dari posisi router, pilihan frekuensi Wi-Fi, sampai kebiasaan mengecek perangkat yang menyedot bandwidth.',
                'body' => $this->article([
                    'Koneksi internet yang terasa lambat tidak selalu disebabkan oleh paket internet. Dalam banyak kasus, masalahnya muncul dari posisi router, terlalu banyak perangkat aktif, interferensi sinyal, atau kabel jaringan yang sudah tidak layak. Karena itu, langkah pertama untuk mendapatkan internet stabil di rumah adalah memeriksa kondisi jaringan dari sisi pengguna.',
                    'Letakkan router di area terbuka, lebih tinggi dari lantai, dan sedekat mungkin dengan titik aktivitas utama. Hindari menaruh router di belakang televisi, di dalam lemari, dekat microwave, atau menempel pada tembok tebal. Sinyal Wi-Fi bekerja lebih baik ketika tidak terhalang benda padat dan tidak bertabrakan dengan perangkat elektronik lain.',
                    'Gunakan jaringan 5 GHz untuk aktivitas yang membutuhkan latensi rendah seperti meeting online, gaming, dan streaming resolusi tinggi. Frekuensi 2.4 GHz tetap berguna untuk jarak lebih jauh dan perangkat IoT, tetapi biasanya lebih padat karena dipakai banyak perangkat rumah tangga.',
                    'Periksa perangkat yang tersambung ke Wi-Fi. Satu ponsel yang sedang backup foto, satu laptop yang mengunduh update besar, atau smart TV yang streaming 4K dapat memengaruhi pengalaman perangkat lain. Jika router mendukung fitur quality of service, prioritaskan perangkat kerja, kelas online, atau perangkat kasir bisnis kecil.',
                    'Restart router secara berkala ketika koneksi terasa tidak normal, tetapi jangan menjadikannya satu-satunya solusi. Jika gangguan sering berulang, cek kabel LAN, adaptor daya, suhu router, dan jumlah perangkat yang terhubung. Router lama yang bekerja 24 jam setiap hari dapat kehilangan performa karena panas dan keterbatasan memori.',
                    'Untuk rumah bertingkat atau bangunan memanjang, pertimbangkan access point tambahan atau mesh Wi-Fi. Repeater murah memang mudah dipasang, tetapi sering mengorbankan kecepatan. Access point kabel lebih stabil karena jalur utama tetap lewat LAN, bukan memantulkan sinyal Wi-Fi yang sudah lemah.',
                    'Terakhir, lakukan speed test dengan benar. Uji memakai kabel LAN langsung ke router untuk mengetahui performa paket utama, lalu bandingkan dengan hasil Wi-Fi dari beberapa ruangan. Cara ini membantu membedakan masalah dari sisi provider, router, atau cakupan Wi-Fi di rumah.',
                    'Dengan pengaturan yang rapi, internet rumah bisa terasa jauh lebih konsisten. Target utamanya bukan hanya angka Mbps tinggi, tetapi ping stabil, jitter rendah, dan sinyal merata di area yang benar-benar dipakai.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => '10 Tips Internet Stabil di Rumah untuk Wi-Fi Lancar',
                'meta_description' => 'Pelajari 10 tips internet stabil di rumah: posisi router, 2.4 GHz vs 5 GHz, QoS, kabel LAN, mesh Wi-Fi, dan cara speed test yang benar.',
                'published_at' => now()->subDays(1)->setTime(8, 30),
            ],
            [
                'title' => 'Apa Itu Wi-Fi 7 dan Kapan Rumah Perlu Upgrade Router?',
                'excerpt' => 'Wi-Fi 7 menawarkan kapasitas lebih besar, latensi lebih rendah, dan multi-link operation. Namun tidak semua rumah harus langsung mengganti router.',
                'body' => $this->article([
                    'Wi-Fi 7 adalah generasi Wi-Fi modern yang dirancang untuk lingkungan dengan banyak perangkat, kebutuhan bandwidth besar, dan aplikasi real-time. Teknologi ini membawa fitur seperti kanal lebih lebar, modulasi lebih efisien, dan multi-link operation yang memungkinkan perangkat memanfaatkan beberapa jalur koneksi secara lebih pintar.',
                    'Bagi pengguna rumahan, manfaat paling terasa bukan sekadar angka kecepatan maksimum. Wi-Fi 7 lebih menarik karena membantu menjaga koneksi tetap responsif ketika rumah dipenuhi ponsel, laptop, smart TV, kamera CCTV, konsol game, dan perangkat smart home. Koneksi yang konsisten sering kali lebih penting daripada hasil speed test sesaat.',
                    'Meski begitu, upgrade router tidak selalu wajib. Jika paket internet masih di bawah 100 Mbps, rumah tidak terlalu padat perangkat, dan router Wi-Fi 5 atau Wi-Fi 6 masih stabil, peningkatan ke Wi-Fi 7 mungkin belum mendesak. Pengguna akan lebih dulu merasakan manfaat dari penempatan router yang benar atau pemasangan access point tambahan.',
                    'Upgrade mulai masuk akal ketika rumah memakai paket berkecepatan tinggi, banyak perangkat aktif bersamaan, sering video conference, bermain game online, atau streaming 4K di beberapa layar. Wi-Fi 7 juga lebih relevan untuk rumah yang ingin siap beberapa tahun ke depan, terutama jika perangkat baru sudah mendukung standar tersebut.',
                    'Sebelum membeli, pastikan perangkat klien juga mendukung Wi-Fi 7. Router canggih tetap bisa melayani perangkat lama, tetapi fitur terbaiknya hanya terasa pada ponsel, laptop, atau adaptor yang kompatibel. Cek juga apakah router memiliki port WAN dan LAN gigabit atau multi-gigabit agar tidak menjadi bottleneck.',
                    'Untuk ISP lokal, edukasi Wi-Fi 7 dapat menjadi konten yang bernilai tinggi karena banyak pelanggan menyamakan internet cepat dengan router mahal. Artikel edukatif membantu pelanggan memahami bahwa performa internet adalah gabungan paket, jaringan fiber, router, posisi perangkat, dan kualitas instalasi.',
                    'Kesimpulannya, Wi-Fi 7 adalah langkah maju yang kuat, tetapi keputusan upgrade harus disesuaikan dengan kebutuhan nyata. Rumah padat perangkat dan paket internet cepat akan mendapat manfaat lebih besar dibanding rumah kecil dengan pemakaian ringan.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1600267165477-6d4cc741b379?auto=format&fit=crop&w=1200&q=80',
                'category' => 'umum',
                'meta_title' => 'Apa Itu Wi-Fi 7? Manfaat dan Waktu Upgrade Router',
                'meta_description' => 'Kenali Wi-Fi 7, manfaatnya untuk rumah padat perangkat, fitur multi-link operation, dan kapan waktu terbaik upgrade router internet.',
                'published_at' => now()->subDays(2)->setTime(9, 10),
            ],
            [
                'title' => 'Fiber Optik vs Wireless: Mana yang Lebih Stabil untuk Internet Rumah dan Bisnis?',
                'excerpt' => 'Perbandingan fiber optik dan wireless dari sisi stabilitas, latensi, kapasitas, biaya instalasi, dan kebutuhan pengguna rumah maupun bisnis.',
                'body' => $this->article([
                    'Fiber optik dan wireless sama-sama dipakai untuk menghadirkan internet, tetapi karakter keduanya berbeda. Fiber optik mengirim data melalui cahaya di dalam kabel kaca atau plastik khusus, sedangkan wireless mengandalkan gelombang radio dari titik pemancar ke penerima. Perbedaan media ini memengaruhi stabilitas, latensi, dan kapasitas jaringan.',
                    'Dari sisi stabilitas, fiber optik biasanya lebih unggul karena tidak mudah terganggu cuaca, kepadatan sinyal, atau halangan bangunan. Selama kabel, konektor, dan perangkat optik dalam kondisi baik, kualitas koneksi dapat dipertahankan secara konsisten. Inilah alasan fiber banyak dipilih untuk rumah, kantor, sekolah, dan bisnis yang membutuhkan internet aktif sepanjang hari.',
                    'Wireless tetap punya kelebihan besar: pemasangan lebih cepat dan fleksibel untuk area yang belum terjangkau kabel. Di wilayah dengan medan sulit, wireless dapat menjadi solusi awal yang ekonomis. Namun performanya sangat bergantung pada line of sight, kualitas radio, interferensi, tinggi tower, dan kondisi cuaca ekstrem.',
                    'Untuk latensi, fiber cenderung memberikan ping lebih rendah dan stabil. Ini penting untuk video conference, kasir online, cloud POS, game online, CCTV cloud, dan aplikasi bisnis yang sensitif terhadap delay. Wireless dapat tetap baik jika desain link benar, tetapi butuh perencanaan frekuensi yang disiplin.',
                    'Bagi pelanggan rumah, pilihan terbaik biasanya fiber jika area sudah tercover. Untuk bisnis, fiber lebih ideal karena mendukung kapasitas besar, monitoring lebih mudah, dan upgrade paket lebih fleksibel. Wireless dapat dijadikan backup link agar operasional tetap berjalan ketika jalur utama mengalami gangguan fisik.',
                    'Komponen penting pada jaringan fiber meliputi OLT, ODP, kabel distribusi, drop core, konektor, splitter, dan ONT di sisi pelanggan. Setiap sambungan harus rapi karena redaman kecil sekalipun dapat memengaruhi kualitas sinyal optik. Instalasi yang bersih akan mengurangi gangguan berulang dan mempercepat proses troubleshooting.',
                    'Kesimpulannya, fiber optik unggul untuk stabilitas jangka panjang, sedangkan wireless unggul dalam kecepatan deployment. Kombinasi keduanya bisa menjadi strategi terbaik untuk ISP, terutama ketika ingin memperluas coverage tanpa mengorbankan kualitas pelanggan prioritas.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Fiber Optik vs Wireless: Internet Mana Lebih Stabil?',
                'meta_description' => 'Bandingkan fiber optik dan wireless untuk internet rumah serta bisnis dari stabilitas, latensi, kapasitas, instalasi, dan biaya.',
                'published_at' => now()->subDays(3)->setTime(10, 0),
            ],
            [
                'title' => 'Mengenal OLT, ODP, ONT, dan Splitter pada Jaringan Internet Fiber',
                'excerpt' => 'Penjelasan sederhana tentang komponen utama jaringan fiber optik ISP: OLT, ODP, ONT, splitter, kabel drop core, dan konektor optik.',
                'body' => $this->article([
                    'Jaringan fiber optik terlihat sederhana dari sisi pelanggan karena hanya ada kabel kecil dan perangkat ONT di rumah. Di balik itu, ada beberapa komponen penting yang bekerja bersama agar internet dapat berjalan stabil dari pusat jaringan ISP sampai ke perangkat pelanggan.',
                    'OLT atau Optical Line Terminal berada di sisi provider. Perangkat ini menjadi pusat distribusi layanan fiber dan mengatur koneksi ke banyak pelanggan. OLT terhubung ke jaringan utama ISP, lalu menyalurkan layanan melalui port optik menuju jalur distribusi.',
                    'ODP atau Optical Distribution Point adalah titik distribusi yang biasanya berada di tiang atau area dekat pelanggan. Dari ODP, teknisi menarik kabel drop core ke rumah atau tempat usaha. ODP yang tertata rapi memudahkan aktivasi pelanggan baru dan mempercepat perbaikan ketika terjadi gangguan.',
                    'ONT atau Optical Network Terminal adalah perangkat di sisi pelanggan. Fungsinya mengubah sinyal optik menjadi koneksi Ethernet dan Wi-Fi yang bisa dipakai oleh ponsel, laptop, router tambahan, CCTV, atau perangkat bisnis. Banyak orang menyebut ONT sebagai modem fiber, meski secara teknis fungsinya berbeda dari modem kabel lama.',
                    'Splitter membagi satu jalur optik menjadi beberapa jalur pelanggan. Komponen ini efisien, tetapi setiap pembagian menambah redaman. Karena itu ISP harus menghitung power budget agar sinyal yang sampai ke pelanggan tetap dalam batas aman.',
                    'Kabel drop core, patch cord, adaptor, dan konektor juga tidak boleh dianggap sepele. Konektor yang kotor, tekukan kabel terlalu tajam, atau sambungan asal-asalan bisa membuat koneksi putus nyambung. Di jaringan fiber, kebersihan dan kerapian instalasi adalah bagian dari performa.',
                    'Memahami komponen ini membantu pelanggan lebih mudah berkomunikasi dengan teknisi. Saat terjadi gangguan, informasi seperti lampu LOS merah pada ONT, kabel tertarik, atau ODP terkena pekerjaan lapangan dapat mempercepat diagnosis.',
                    'Bagi ISP, artikel edukasi komponen jaringan seperti ini juga membangun kepercayaan. Pelanggan melihat bahwa layanan internet bukan hanya menjual Mbps, tetapi mengelola infrastruktur yang membutuhkan perencanaan, perawatan, dan standar teknis.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80',
                'category' => 'umum',
                'meta_title' => 'Fungsi OLT, ODP, ONT, dan Splitter Jaringan Fiber',
                'meta_description' => 'Mengenal OLT, ODP, ONT, splitter, drop core, dan konektor optik pada jaringan internet fiber agar pelanggan paham penyebab gangguan.',
                'published_at' => now()->subDays(4)->setTime(8, 45),
            ],
            [
                'title' => 'Cara Mengamankan Wi-Fi Rumah dari Pembobol dan Perangkat Tidak Dikenal',
                'excerpt' => 'Langkah SEO-friendly dan praktis mengamankan Wi-Fi rumah: password kuat, WPA2/WPA3, guest network, update router, dan cek perangkat asing.',
                'body' => $this->article([
                    'Wi-Fi rumah yang tidak aman dapat membuat koneksi melambat, kuota perangkat tersedot, dan data pribadi lebih rentan. Banyak kasus internet terasa lambat ternyata bukan karena gangguan provider, melainkan karena ada perangkat tidak dikenal yang ikut memakai jaringan.',
                    'Langkah pertama adalah mengganti nama Wi-Fi dan password bawaan. Gunakan kata sandi minimal 12 karakter dengan kombinasi huruf besar, huruf kecil, angka, dan simbol. Hindari password yang mudah ditebak seperti nomor rumah, tanggal lahir, nama anak, atau nama Wi-Fi yang sama dengan password.',
                    'Aktifkan WPA2-PSK atau WPA3 jika tersedia. Hindari mode keamanan lama seperti WEP karena sudah tidak layak dipakai. Jika router menyediakan pilihan mixed mode, gunakan hanya jika masih ada perangkat lama yang benar-benar membutuhkan kompatibilitas.',
                    'Matikan WPS apabila tidak diperlukan. Fitur ini memudahkan perangkat tersambung, tetapi pada beberapa router bisa menjadi celah keamanan. Untuk penggunaan rumah, memasukkan password secara manual jauh lebih aman daripada membiarkan WPS aktif sepanjang waktu.',
                    'Gunakan guest network untuk tamu. Dengan jaringan tamu, perangkat pengunjung tidak perlu masuk ke jaringan utama yang berisi laptop kerja, kamera CCTV, printer, atau perangkat smart home. Beberapa router juga memungkinkan pembatasan kecepatan pada guest network agar aktivitas utama tetap lancar.',
                    'Cek daftar perangkat secara berkala melalui halaman admin router atau aplikasi manajemen router. Jika menemukan nama perangkat asing, ubah password dan restart koneksi. Untuk keamanan tambahan, update firmware router agar mendapatkan perbaikan bug dan peningkatan stabilitas.',
                    'Jangan lupa amankan akun admin router. Banyak pengguna mengganti password Wi-Fi tetapi membiarkan username dan password admin tetap bawaan. Ini berisiko karena siapa pun yang sudah tersambung ke jaringan dapat mencoba masuk ke pengaturan router.',
                    'Keamanan Wi-Fi adalah kebiasaan, bukan tindakan sekali selesai. Dengan password kuat, enkripsi modern, guest network, dan pengecekan berkala, internet rumah menjadi lebih aman, stabil, dan nyaman dipakai keluarga.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Cara Mengamankan Wi-Fi Rumah dari Pembobol',
                'meta_description' => 'Panduan mengamankan Wi-Fi rumah dengan password kuat, WPA2/WPA3, guest network, update firmware, dan cek perangkat tidak dikenal.',
                'published_at' => now()->subDays(5)->setTime(11, 20),
            ],
            [
                'title' => 'AI di Jaringan Internet: Bagaimana Kecerdasan Buatan Membantu ISP Menjaga Koneksi Stabil',
                'excerpt' => 'AI mulai dipakai untuk monitoring jaringan, prediksi gangguan, analisis trafik, chatbot layanan pelanggan, dan optimasi kapasitas ISP.',
                'body' => $this->article([
                    'Kecerdasan buatan tidak hanya hadir di aplikasi chat dan pembuat gambar. Di industri jaringan internet, AI mulai digunakan untuk membaca pola trafik, mendeteksi anomali, memprediksi gangguan, dan membantu tim teknis mengambil keputusan lebih cepat.',
                    'Salah satu penggunaan paling relevan adalah monitoring jaringan. Sistem dapat mempelajari pola normal dari perangkat seperti router, OLT, server, dan access point. Ketika terjadi perubahan tidak wajar seperti lonjakan packet loss, port flapping, atau pemakaian bandwidth yang tiba-tiba melonjak, sistem bisa memberi peringatan lebih awal.',
                    'AI juga membantu dalam prediksi gangguan. Misalnya, jika redaman optik pelanggan perlahan memburuk dari hari ke hari, sistem dapat menandai kemungkinan kabel tertekuk, konektor kotor, atau sambungan mulai bermasalah sebelum pelanggan benar-benar kehilangan koneksi.',
                    'Di sisi layanan pelanggan, chatbot berbasis AI dapat membantu menjawab pertanyaan dasar seperti cara restart ONT, cek lampu indikator, informasi tagihan, atau status gangguan area. Namun chatbot harus tetap terhubung dengan data operasional yang benar agar jawaban tidak sekadar terdengar pintar, tetapi benar-benar membantu.',
                    'Untuk optimasi kapasitas, AI dapat membaca jam sibuk, area dengan pertumbuhan pelanggan tinggi, dan rute yang mulai padat. Data ini membantu ISP menentukan kapan perlu upgrade backhaul, menambah perangkat distribusi, atau menyeimbangkan trafik antar jalur.',
                    'Meski menjanjikan, AI bukan pengganti desain jaringan yang baik. Kabel tetap harus rapi, power budget fiber tetap harus dihitung, perangkat harus dipilih sesuai kapasitas, dan tim lapangan tetap membutuhkan SOP yang jelas. AI bekerja paling baik ketika data dasar akurat dan proses operasional sudah tertata.',
                    'Bagi pelanggan, manfaat akhirnya adalah gangguan lebih cepat terdeteksi, respon teknis lebih tepat, dan layanan lebih konsisten. Bagi ISP lokal, adopsi AI bertahap dapat dimulai dari dashboard monitoring, klasifikasi tiket, dan laporan performa jaringan harian.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
                'category' => 'umum',
                'meta_title' => 'AI di Jaringan Internet untuk ISP Lebih Stabil',
                'meta_description' => 'Pelajari bagaimana AI membantu ISP menjaga internet stabil lewat monitoring jaringan, prediksi gangguan, chatbot, dan optimasi trafik.',
                'published_at' => now()->subDays(6)->setTime(9, 35),
            ],
            [
                'title' => 'Internet untuk Smart Home: Tips Menyiapkan Wi-Fi untuk CCTV, Smart TV, dan Perangkat IoT',
                'excerpt' => 'Rumah pintar membutuhkan Wi-Fi stabil. Simak cara menyiapkan jaringan untuk CCTV, smart TV, lampu pintar, speaker pintar, dan perangkat IoT lainnya.',
                'body' => $this->article([
                    'Perangkat smart home semakin umum: CCTV Wi-Fi, smart TV, lampu pintar, speaker pintar, door lock, sensor, dan perangkat otomatisasi rumah. Semua perangkat ini bergantung pada jaringan yang stabil. Jika Wi-Fi tidak dirancang dengan baik, rumah pintar justru terasa merepotkan karena perangkat sering offline.',
                    'Mulailah dengan memisahkan perangkat berdasarkan kebutuhan. Smart TV, konsol game, dan laptop kerja membutuhkan bandwidth lebih besar. CCTV membutuhkan koneksi stabil sepanjang hari. Lampu pintar dan sensor biasanya tidak butuh kecepatan tinggi, tetapi perlu sinyal yang konsisten.',
                    'Gunakan frekuensi 2.4 GHz untuk perangkat IoT yang jaraknya jauh atau tidak membutuhkan bandwidth besar. Banyak perangkat smart home masih hanya mendukung 2.4 GHz karena frekuensi ini lebih luas jangkauannya. Untuk smart TV dan perangkat streaming, gunakan 5 GHz atau kabel LAN jika memungkinkan.',
                    'Buat jaringan tamu atau jaringan khusus IoT jika router mendukung. Pemisahan ini membantu keamanan karena perangkat pintar tidak harus berada di jaringan yang sama dengan laptop kerja atau perangkat berisi data penting. Jika salah satu perangkat IoT bermasalah, dampaknya terhadap jaringan utama bisa dibatasi.',
                    'Perhatikan upload speed untuk CCTV cloud. Banyak pelanggan hanya melihat angka download, padahal kamera yang mengirim rekaman ke cloud membutuhkan upload stabil. Semakin banyak kamera dan semakin tinggi resolusinya, semakin besar kebutuhan upload.',
                    'Untuk rumah besar, gunakan access point tambahan. Jangan memaksa satu router melayani semua sudut rumah jika sinyal sudah lemah. Perangkat IoT yang berada di teras, garasi, atau lantai atas sering menjadi sumber masalah karena berada di batas cakupan sinyal.',
                    'Update firmware perangkat pintar dan router secara berkala. Selain memperbaiki bug, update juga menutup celah keamanan. Gunakan password berbeda untuk akun aplikasi smart home dan aktifkan verifikasi dua langkah jika tersedia.',
                    'Internet smart home yang baik tidak harus selalu memakai paket paling mahal. Yang paling penting adalah desain Wi-Fi yang sesuai, pemisahan perangkat, cakupan sinyal merata, dan pemahaman kebutuhan upload serta latency.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Internet Smart Home untuk CCTV dan Perangkat IoT',
                'meta_description' => 'Tips menyiapkan Wi-Fi smart home untuk CCTV, smart TV, lampu pintar, dan IoT agar koneksi stabil, aman, dan tidak mudah offline.',
                'published_at' => now()->subDays(7)->setTime(14, 0),
            ],
            [
                'title' => 'Kenapa Ping Rendah Penting untuk Game Online, Meeting, dan Aplikasi Real-Time?',
                'excerpt' => 'Kecepatan internet bukan hanya Mbps. Ping, jitter, dan packet loss menentukan kualitas game online, video call, VoIP, CCTV, dan kerja remote.',
                'body' => $this->article([
                    'Banyak orang menilai kualitas internet hanya dari angka Mbps. Padahal untuk aktivitas real-time seperti game online, video meeting, telepon VoIP, remote desktop, dan live streaming, ping rendah dan stabil sering lebih penting daripada download besar.',
                    'Ping adalah waktu yang dibutuhkan data untuk pergi dari perangkat ke server dan kembali lagi. Semakin rendah ping, semakin cepat respons yang terasa. Dalam game online, ping tinggi menyebabkan delay saat menekan tombol. Dalam meeting, ping tinggi bisa membuat suara terlambat dan percakapan saling tumpang tindih.',
                    'Jitter adalah perubahan ping dari waktu ke waktu. Ping 20 ms yang stabil biasanya lebih nyaman daripada ping yang naik turun dari 20 ms ke 200 ms. Jitter tinggi membuat suara patah-patah, video tersendat, dan game terasa tidak konsisten.',
                    'Packet loss terjadi ketika sebagian paket data hilang di perjalanan. Dampaknya bisa lebih mengganggu daripada koneksi lambat. Pada video call, packet loss membuat suara hilang sebentar. Pada game, karakter bisa berpindah tiba-tiba. Pada aplikasi bisnis, sinkronisasi data bisa gagal.',
                    'Penyebab ping tinggi bisa berasal dari Wi-Fi lemah, router kelebihan beban, kabel LAN rusak, server tujuan jauh, atau rute jaringan sedang padat. Karena itu, diagnosis harus dilakukan bertahap: uji lewat kabel LAN, cek perangkat lain yang memakai bandwidth besar, lalu bandingkan hasil ke beberapa server.',
                    'Untuk pengguna rumah, cara termudah menurunkan ping adalah memakai kabel LAN untuk perangkat penting, memilih posisi router yang tepat, menggunakan 5 GHz ketika jarak dekat, dan membatasi download besar saat meeting atau gaming. Untuk bisnis, router dengan QoS dan manajemen bandwidth lebih penting.',
                    'Provider internet yang baik tidak hanya mengejar bandwidth tinggi, tetapi juga menjaga kualitas routing, kapasitas backhaul, dan monitoring gangguan. Pelanggan akan merasakan kualitas tersebut ketika koneksi tetap responsif pada jam sibuk.',
                    'Kesimpulannya, Mbps menjelaskan kapasitas, sedangkan ping, jitter, dan packet loss menjelaskan kenyamanan. Untuk pengalaman internet modern, ketiganya harus diperhatikan bersama.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Ping Rendah untuk Game Online dan Meeting Stabil',
                'meta_description' => 'Kenali ping, jitter, dan packet loss. Pelajari kenapa latency rendah penting untuk game online, meeting, VoIP, dan kerja remote.',
                'published_at' => now()->subDays(8)->setTime(15, 15),
            ],
            [
                'title' => 'Checklist Memilih Paket Internet Rumah: Jangan Hanya Lihat Mbps',
                'excerpt' => 'Panduan memilih paket internet rumah berdasarkan jumlah pengguna, jenis aktivitas, stabilitas, upload, FUP, router, dan layanan teknis.',
                'body' => $this->article([
                    'Memilih paket internet rumah sering terlihat sederhana: semakin besar Mbps, semakin baik. Kenyataannya, paket terbaik adalah paket yang sesuai dengan jumlah pengguna, jenis aktivitas, perangkat, dan kualitas jaringan di lokasi rumah.',
                    'Hitung dulu jumlah pengguna aktif. Rumah dengan dua orang yang sesekali streaming tentu berbeda dengan rumah berisi keluarga besar, kelas online, kerja remote, CCTV cloud, dan smart TV. Setiap perangkat aktif menambah kebutuhan bandwidth dan membuat kualitas router semakin penting.',
                    'Perhatikan jenis aktivitas. Browsing, chat, dan media sosial tidak membutuhkan bandwidth sebesar streaming 4K, upload video, backup cloud, meeting harian, atau game online. Untuk keluarga yang sering meeting dan upload file, upload speed perlu diperhatikan, bukan hanya download.',
                    'Tanyakan teknologi jaringan yang digunakan. Fiber optik biasanya lebih stabil untuk penggunaan jangka panjang, terutama jika instalasi dan perangkat distribusinya baik. Jika layanan memakai wireless, pastikan provider memiliki desain link yang rapi dan dukungan teknis yang jelas.',
                    'Cek kebijakan FUP atau batas pemakaian wajar jika ada. Paket terlihat murah bisa terasa kurang nyaman jika performa turun setelah pemakaian tertentu. Transparansi kebijakan lebih penting daripada promosi besar yang tidak menjelaskan batas layanan.',
                    'Pastikan router sesuai kebutuhan rumah. Paket cepat tidak akan maksimal jika router hanya mendukung standar lama atau cakupannya terlalu kecil. Untuk rumah besar, biaya access point tambahan bisa lebih berguna daripada memaksa satu router murah bekerja sendirian.',
                    'Lihat juga kualitas layanan teknis. Internet adalah layanan berkelanjutan, bukan produk sekali beli. Kecepatan respon gangguan, kanal komunikasi, jadwal teknisi, dan informasi maintenance sangat memengaruhi kepuasan pelanggan.',
                    'Checklist terbaik sebelum berlangganan adalah: jumlah pengguna, aktivitas utama, kebutuhan upload, cakupan Wi-Fi, jenis jaringan, kebijakan FUP, kualitas router, dan reputasi support. Dengan cara ini, pelanggan memilih paket berdasarkan kebutuhan nyata, bukan sekadar angka promosi.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Checklist Memilih Paket Internet Rumah Terbaik',
                'meta_description' => 'Jangan hanya lihat Mbps. Gunakan checklist paket internet rumah: pengguna, aktivitas, upload, FUP, router, fiber, dan layanan teknis.',
                'published_at' => now()->subDays(9)->setTime(7, 50),
            ],
            [
                'title' => 'Tren Teknologi Internet 2026: Wi-Fi 7, AI Network Monitoring, Fiber, dan Keamanan Digital',
                'excerpt' => 'Ringkasan tren teknologi internet 2026 yang relevan untuk pengguna rumah, bisnis kecil, dan ISP lokal: Wi-Fi 7, fiber, AI, IoT, dan cybersecurity.',
                'body' => $this->article([
                    'Tahun 2026 memperlihatkan arah yang jelas dalam industri internet: koneksi harus lebih stabil, lebih aman, dan lebih siap menghadapi perangkat yang semakin banyak. Pengguna tidak hanya membutuhkan download cepat, tetapi juga latensi rendah, upload konsisten, cakupan Wi-Fi merata, dan perlindungan dari ancaman digital.',
                    'Wi-Fi 7 menjadi salah satu topik utama karena menawarkan kapasitas lebih besar dan pengalaman lebih responsif di rumah padat perangkat. Namun tren berikutnya tidak berhenti pada kecepatan. Industri mulai bergerak ke arah Wi-Fi yang lebih andal, lebih pintar mengelola interferensi, dan lebih baik untuk lingkungan dengan banyak access point.',
                    'Fiber optik tetap menjadi tulang punggung konektivitas. Pertumbuhan aplikasi AI, cloud, streaming, CCTV, dan kerja jarak jauh mendorong kebutuhan bandwidth yang lebih besar. Untuk ISP, investasi pada jaringan fiber yang rapi, monitoring power optik, dan kapasitas backhaul menjadi semakin penting.',
                    'AI network monitoring juga semakin relevan. Sistem yang mampu membaca pola trafik, mendeteksi anomali, mengelompokkan tiket gangguan, dan memprediksi area berisiko dapat membantu tim teknis bekerja lebih cepat. Bukan berarti semua keputusan diserahkan ke AI, tetapi data yang baik membuat prioritas kerja lebih jelas.',
                    'Smart home dan IoT terus bertambah. CCTV, sensor, smart TV, dan perangkat otomasi rumah membuat jaringan rumah lebih kompleks. Pelanggan mulai membutuhkan edukasi tentang guest network, pemisahan perangkat IoT, keamanan password, dan pentingnya upload speed.',
                    'Keamanan digital menjadi kebutuhan dasar. Router dengan firmware usang, password lemah, dan perangkat tidak dikenal dapat menurunkan kualitas koneksi sekaligus membuka risiko privasi. ISP yang aktif mengedukasi pelanggan tentang keamanan Wi-Fi akan memiliki nilai tambah di mata pengguna.',
                    'Bagi bisnis kecil, internet stabil menjadi bagian dari operasional. Kasir online, marketplace, WhatsApp Business, absensi, CCTV, dan aplikasi cloud tidak bisa berjalan baik jika koneksi sering putus. Karena itu, paket bisnis, backup link, dan support responsif semakin penting.',
                    'Tren 2026 menegaskan satu hal: masa depan internet bukan hanya lebih cepat, tetapi lebih cerdas dan lebih dapat diandalkan. Provider yang mampu menggabungkan fiber kuat, Wi-Fi modern, monitoring aktif, dan edukasi pelanggan akan lebih mudah memenangkan kepercayaan pasar.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
                'category' => 'umum',
                'meta_title' => 'Tren Teknologi Internet 2026: Wi-Fi 7, AI, Fiber',
                'meta_description' => 'Simak tren teknologi internet 2026: Wi-Fi 7, AI network monitoring, fiber optik, smart home, IoT, keamanan digital, dan bisnis kecil.',
                'published_at' => now()->subDays(10)->setTime(8, 0),
            ],
            [
                'title' => 'Cara Cek Kecepatan Internet yang Benar agar Hasil Speed Test Tidak Menyesatkan',
                'excerpt' => 'Speed test sering dipakai untuk menilai kualitas internet, tetapi hasilnya bisa keliru jika cara pengujiannya salah. Simak langkah cek internet yang akurat.',
                'body' => $this->article([
                    'Speed test adalah alat yang berguna, tetapi bukan satu-satunya ukuran kualitas internet. Banyak pengguna langsung menyimpulkan internet bermasalah ketika angka download turun, padahal pengujian dilakukan lewat Wi-Fi lemah, server test terlalu jauh, atau ada perangkat lain yang sedang mengunduh file besar.',
                    'Langkah paling akurat adalah menguji lewat kabel LAN langsung dari router atau ONT ke laptop. Cara ini membantu mengetahui performa jalur utama sebelum sinyal Wi-Fi ikut memengaruhi hasil. Jika lewat kabel hasilnya normal tetapi lewat Wi-Fi rendah, masalah kemungkinan berada pada cakupan Wi-Fi, interferensi, atau posisi router.',
                    'Tutup aplikasi yang menggunakan internet sebelum test. Sinkronisasi cloud, update sistem, streaming, dan backup foto dapat mengambil bandwidth tanpa terlihat. Pastikan juga tidak ada perangkat lain yang sedang memakai koneksi berat, terutama smart TV dan konsol game.',
                    'Pilih server speed test yang dekat secara geografis dan gunakan lebih dari satu server sebagai pembanding. Server yang terlalu jauh dapat menambah latensi dan membuat hasil terlihat lebih buruk dari kondisi sebenarnya.',
                    'Lakukan test beberapa kali di jam berbeda. Pengujian pagi, siang, malam, dan saat jam sibuk akan memberi gambaran lebih adil. Internet yang baik bukan hanya cepat sesaat, tetapi konsisten ketika banyak pengguna aktif.',
                    'Catat tiga metrik utama: download, upload, dan ping. Download penting untuk streaming dan browsing, upload penting untuk video call serta backup cloud, sedangkan ping penting untuk game online dan aplikasi real-time.',
                    'Untuk laporan ke provider, sertakan hasil test kabel LAN, waktu pengujian, perangkat yang dipakai, dan screenshot indikator router jika ada. Informasi lengkap membuat tim teknis lebih cepat membedakan gangguan jaringan dari masalah perangkat lokal.',
                    'Dengan metode yang benar, speed test menjadi alat diagnosis yang kuat. Pengguna bisa mengambil keputusan lebih tepat, apakah perlu memperbaiki Wi-Fi rumah, mengganti kabel, upgrade router, atau melapor ke provider.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Cara Cek Kecepatan Internet yang Benar',
                'meta_description' => 'Panduan cek kecepatan internet yang akurat: speed test via LAN, pilih server dekat, cek ping, upload, download, dan waktu pengujian.',
                'published_at' => now()->setTime(7, 15),
            ],
            [
                'title' => 'Penyebab Wi-Fi Lemot Padahal Sinyal Penuh dan Cara Mengatasinya',
                'excerpt' => 'Sinyal Wi-Fi penuh belum tentu koneksi cepat. Kenali penyebab Wi-Fi lemot seperti interferensi, router overload, DNS lambat, dan channel padat.',
                'body' => $this->article([
                    'Ikon Wi-Fi penuh sering membuat pengguna mengira koneksi pasti cepat. Padahal sinyal penuh hanya menunjukkan perangkat dekat dengan router, bukan menjamin jalur internet bebas masalah. Wi-Fi bisa tetap lemot karena channel padat, router kelebihan beban, DNS lambat, atau perangkat lain menghabiskan bandwidth.',
                    'Penyebab paling umum adalah interferensi. Di area padat rumah, kos, atau ruko, banyak router memakai channel yang sama. Akibatnya perangkat harus bergantian mengirim data dan koneksi terasa lambat meski indikator sinyal kuat.',
                    'Router yang terlalu lama menyala juga bisa overload, terutama jika banyak perangkat tersambung. Setiap ponsel, laptop, CCTV, dan smart TV menambah beban memori serta proses routing. Router kelas rumahan punya batas kemampuan, sehingga performanya bisa turun ketika perangkat aktif terlalu banyak.',
                    'Periksa apakah ada perangkat yang sedang download besar, update game, streaming 4K, atau backup file ke cloud. Aktivitas semacam ini bisa membuat pengguna lain merasa internet melambat. Fitur QoS di router dapat membantu memberi prioritas ke video call, kerja online, atau perangkat utama.',
                    'DNS juga dapat memengaruhi pengalaman browsing. Jika membuka situs terasa lama tetapi speed test normal, coba gunakan DNS yang lebih responsif atau aktifkan DNS otomatis dari provider jika sudah dioptimalkan.',
                    'Solusi praktisnya adalah mengubah posisi router, memisahkan jaringan 2.4 GHz dan 5 GHz, mengganti channel Wi-Fi, membatasi perangkat tidak dikenal, dan memakai kabel LAN untuk perangkat penting seperti PC kerja atau smart TV.',
                    'Jika rumah luas, satu router mungkin tidak cukup. Access point tambahan dengan kabel LAN biasanya lebih stabil daripada repeater murah. Targetnya bukan sekadar sinyal penuh, tetapi throughput dan latency yang konsisten di ruangan yang sering dipakai.',
                    'Wi-Fi lemot dengan sinyal penuh adalah masalah yang bisa dianalisis. Dengan memahami perbedaan sinyal, bandwidth, interferensi, dan beban router, pengguna dapat memperbaiki koneksi tanpa langsung menyalahkan paket internet.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Wi-Fi Lemot Padahal Sinyal Penuh? Ini Penyebabnya',
                'meta_description' => 'Kenali penyebab Wi-Fi lemot meski sinyal penuh: interferensi, channel padat, router overload, DNS lambat, dan solusi praktisnya.',
                'published_at' => now()->setTime(8, 10),
            ],
            [
                'title' => 'Apa Itu Mesh Wi-Fi dan Bedanya dengan Repeater Biasa?',
                'excerpt' => 'Mesh Wi-Fi semakin populer untuk rumah besar. Pahami perbedaan mesh, repeater, dan access point agar tidak salah memilih solusi Wi-Fi.',
                'body' => $this->article([
                    'Mesh Wi-Fi adalah sistem jaringan nirkabel yang menggunakan beberapa node untuk memperluas cakupan internet di rumah atau kantor kecil. Berbeda dari satu router tunggal, mesh dirancang agar perangkat bisa berpindah dari satu node ke node lain dengan lebih mulus.',
                    'Repeater biasa bekerja dengan menangkap sinyal Wi-Fi lalu memancarkannya ulang. Cara ini mudah dipasang, tetapi sering menurunkan kecepatan karena jalur yang sama dipakai untuk menerima dan mengirim data. Jika repeater ditempatkan di area yang sinyalnya sudah lemah, hasilnya tetap tidak optimal.',
                    'Mesh Wi-Fi lebih pintar dalam mengelola perpindahan perangkat. Sistem mesh biasanya memakai satu nama jaringan dan mengarahkan perangkat ke node terbaik. Pengguna tidak perlu mengganti jaringan manual ketika pindah ruangan.',
                    'Meski begitu, mesh bukan selalu solusi terbaik. Jika memungkinkan menarik kabel LAN, access point kabel tetap menjadi pilihan paling stabil. Backhaul kabel membuat node tidak bergantung pada kualitas sinyal antar perangkat, sehingga performa lebih konsisten.',
                    'Mesh cocok untuk rumah bertingkat, bangunan memanjang, atau keluarga yang ingin instalasi rapi tanpa banyak konfigurasi. Mesh juga cocok ketika perangkat sering berpindah ruangan, seperti ponsel dan tablet.',
                    'Sebelum membeli mesh, cek dukungan Wi-Fi, jumlah port LAN, fitur parental control, guest network, dan kemampuan backhaul. Jangan hanya melihat klaim luas area karena kondisi tembok, lantai beton, dan interferensi dapat mengubah hasil nyata.',
                    'Penempatan node sangat penting. Letakkan node kedua di area yang masih menerima sinyal kuat dari node utama, bukan di titik mati. Node yang dipasang di area blank spot hanya akan memperluas sinyal yang sudah buruk.',
                    'Kesimpulannya, mesh Wi-Fi lebih nyaman daripada repeater biasa untuk banyak rumah modern. Namun untuk performa terbaik, desain penempatan dan pilihan backhaul tetap menentukan hasil akhir.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Apa Itu Mesh Wi-Fi? Beda Mesh dan Repeater',
                'meta_description' => 'Pelajari fungsi mesh Wi-Fi, perbedaannya dengan repeater dan access point, serta kapan rumah perlu memakai sistem mesh.',
                'published_at' => now()->setTime(9, 5),
            ],
            [
                'title' => 'Panduan Memilih Router untuk Paket Internet Fiber 100 Mbps sampai 1 Gbps',
                'excerpt' => 'Router menentukan pengalaman internet fiber. Simak spesifikasi yang perlu dicek untuk paket 100 Mbps, 300 Mbps, 500 Mbps, hingga 1 Gbps.',
                'body' => $this->article([
                    'Paket internet fiber cepat tidak akan terasa maksimal jika router yang dipakai tidak sesuai. Banyak pengguna upgrade paket, tetapi masih memakai router lama dengan port 100 Mbps atau Wi-Fi generasi lama. Akibatnya kecepatan yang diterima perangkat jauh di bawah potensi paket.',
                    'Untuk paket 100 Mbps, pastikan router minimal memiliki port fast ethernet yang stabil, tetapi gigabit ethernet lebih disarankan agar ada ruang untuk upgrade. Untuk paket di atas 100 Mbps, port gigabit sudah menjadi kebutuhan wajib.',
                    'Untuk paket 300 sampai 500 Mbps, pilih router dual-band dengan Wi-Fi 5 atau Wi-Fi 6. Frekuensi 5 GHz penting karena 2.4 GHz biasanya tidak mampu menjaga throughput tinggi di area padat. Router juga harus punya prosesor dan memori cukup agar tidak drop saat banyak perangkat aktif.',
                    'Untuk paket mendekati 1 Gbps, gunakan router dengan port WAN gigabit, port LAN gigabit, Wi-Fi 6 atau lebih baru, dan kemampuan menangani NAT throughput tinggi. Jika banyak perangkat kabel seperti PC, NAS, atau CCTV NVR, pertimbangkan switch gigabit tambahan.',
                    'Jumlah antena bukan satu-satunya ukuran kualitas. Yang lebih penting adalah standar Wi-Fi, kualitas chipset, kapasitas CPU, firmware, fitur QoS, guest network, parental control, dan update keamanan.',
                    'Rumah besar membutuhkan strategi cakupan. Daripada membeli router mahal tetapi ditempatkan di sudut rumah, lebih baik memakai router utama yang baik ditambah access point kabel atau mesh dengan backhaul yang benar.',
                    'Perhatikan juga posisi ONT dari provider. Jika ONT berada di titik kurang ideal, router tambahan dapat ditempatkan di area tengah rumah dengan kabel LAN. Penataan fisik sering memberi peningkatan lebih terasa daripada upgrade perangkat secara asal.',
                    'Memilih router harus mengikuti kebutuhan paket, luas rumah, jumlah perangkat, dan jenis aktivitas. Dengan router yang tepat, internet fiber terasa stabil, cepat, dan siap untuk kebutuhan beberapa tahun ke depan.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1597852074816-d933c7d2b988?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Router Terbaik untuk Internet Fiber 100 Mbps-1 Gbps',
                'meta_description' => 'Panduan memilih router untuk paket fiber 100 Mbps, 300 Mbps, 500 Mbps, sampai 1 Gbps berdasarkan port, Wi-Fi, dan kebutuhan rumah.',
                'published_at' => now()->setTime(10, 0),
            ],
            [
                'title' => 'Kenali Lampu Indikator ONT Fiber: Power, PON, LOS, LAN, dan Wi-Fi',
                'excerpt' => 'Lampu indikator ONT membantu membaca kondisi internet fiber. Pelajari arti Power, PON, LOS, LAN, Wi-Fi, dan kapan perlu menghubungi teknisi.',
                'body' => $this->article([
                    'ONT adalah perangkat penting pada layanan internet fiber di sisi pelanggan. Lampu indikator di ONT sebenarnya memberi petunjuk awal tentang kondisi koneksi, sehingga pengguna bisa menjelaskan masalah lebih jelas ketika menghubungi layanan teknis.',
                    'Lampu Power menunjukkan perangkat menyala. Jika mati, periksa adaptor, stop kontak, dan tombol power. Jangan memakai adaptor sembarangan karena tegangan yang tidak sesuai dapat merusak perangkat.',
                    'Lampu PON menandakan koneksi optik ke jaringan provider. Pada kondisi normal, lampu PON biasanya menyala stabil. Jika PON berkedip terus atau mati, kemungkinan ONT belum tersambung sempurna ke jaringan fiber.',
                    'Lampu LOS adalah indikator yang perlu diperhatikan. Jika LOS merah atau berkedip, biasanya ada masalah sinyal optik seperti kabel fiber putus, konektor lepas, ODP bermasalah, atau redaman terlalu tinggi. Pada kondisi ini pengguna sebaiknya tidak mencabut pasang kabel fiber terlalu sering.',
                    'Lampu LAN menunjukkan koneksi kabel ke perangkat seperti router tambahan, PC, switch, atau smart TV. Jika kabel terpasang tetapi LAN mati, coba cek kabel, port, dan perangkat tujuan.',
                    'Lampu Wi-Fi menandakan jaringan nirkabel aktif. Jika internet lewat kabel normal tetapi Wi-Fi tidak muncul, kemungkinan fitur Wi-Fi mati, nama jaringan berubah, atau router mengalami gangguan konfigurasi.',
                    'Saat melapor ke provider, sebutkan status lampu indikator dengan jelas. Contohnya: Power nyala, PON mati, LOS merah, LAN nyala. Informasi ini membantu teknisi menentukan apakah perlu perbaikan konfigurasi, pengecekan kabel, atau kunjungan lapangan.',
                    'Memahami lampu ONT membuat troubleshooting lebih cepat. Pelanggan tidak perlu menebak-nebak, dan tim teknis dapat merespon dengan langkah yang lebih tepat.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1597733336794-12d05021d510?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Arti Lampu ONT Fiber: Power, PON, LOS, LAN',
                'meta_description' => 'Kenali arti lampu indikator ONT fiber seperti Power, PON, LOS, LAN, dan Wi-Fi untuk mempercepat troubleshooting internet.',
                'published_at' => now()->setTime(11, 0),
            ],
            [
                'title' => 'Internet Bisnis Kecil: Kapan Perlu Paket Dedicated atau Backup Link?',
                'excerpt' => 'Bisnis kecil makin bergantung pada internet. Pelajari kapan perlu paket dedicated, IP publik, backup link, dan SLA untuk operasional harian.',
                'body' => $this->article([
                    'Banyak bisnis kecil bergantung pada internet untuk kasir online, marketplace, WhatsApp Business, CCTV, absensi, pembayaran digital, dan aplikasi cloud. Ketika koneksi putus, operasional bisa langsung terganggu. Karena itu, memilih layanan internet untuk bisnis tidak cukup hanya melihat harga paket rumahan.',
                    'Paket dedicated biasanya menawarkan alokasi bandwidth lebih konsisten dan dukungan teknis yang lebih terukur. Bisnis yang memakai aplikasi cloud sepanjang hari, mengirim data besar, atau membutuhkan akses jarak jauh perlu mempertimbangkan paket dengan kualitas layanan lebih tinggi.',
                    'Backup link diperlukan ketika internet menjadi bagian kritis dari operasional. Toko, kantor, klinik, sekolah, dan gudang bisa memakai koneksi cadangan dari jalur berbeda agar tetap berjalan saat jalur utama bermasalah.',
                    'IP publik dibutuhkan untuk kebutuhan tertentu seperti CCTV remote, VPN kantor, server internal, atau integrasi sistem. Namun IP publik juga membutuhkan pengamanan lebih baik, termasuk firewall dan password kuat.',
                    'SLA atau service level agreement penting untuk bisnis yang membutuhkan kepastian respon. SLA membantu menyamakan ekspektasi antara pelanggan dan provider terkait prioritas penanganan, waktu respon, dan ruang lingkup dukungan.',
                    'Manajemen jaringan lokal juga tidak boleh diabaikan. Router bisnis, switch yang baik, segmentasi Wi-Fi tamu, dan UPS untuk perangkat jaringan dapat membuat koneksi lebih stabil saat listrik tidak ideal atau perangkat ramai dipakai.',
                    'Bisnis kecil sebaiknya menghitung biaya downtime. Jika internet mati satu jam membuat transaksi hilang lebih besar daripada biaya backup link, maka koneksi cadangan bukan pengeluaran tambahan, melainkan perlindungan operasional.',
                    'Internet bisnis yang baik mengutamakan stabilitas, dukungan, keamanan, dan rencana cadangan. Mbps tetap penting, tetapi keberlanjutan operasional jauh lebih penting untuk pelanggan bisnis.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80',
                'category' => 'umum',
                'meta_title' => 'Internet Bisnis Kecil: Dedicated dan Backup Link',
                'meta_description' => 'Panduan internet bisnis kecil: kapan perlu paket dedicated, backup link, IP publik, SLA, router bisnis, dan keamanan jaringan.',
                'published_at' => now()->setTime(12, 5),
            ],
            [
                'title' => 'Bandwidth Management untuk Rumah Ramai: Agar Meeting Tidak Kalah oleh Streaming',
                'excerpt' => 'Rumah dengan banyak pengguna perlu manajemen bandwidth. Simak cara membagi prioritas internet untuk meeting, sekolah online, streaming, dan game.',
                'body' => $this->article([
                    'Rumah modern sering memiliki banyak perangkat yang aktif bersamaan. Satu orang meeting online, anak menonton video, smart TV streaming, ponsel backup foto, dan konsol mengunduh update game. Tanpa pengaturan, aktivitas berat bisa membuat koneksi semua orang terasa buruk.',
                    'Bandwidth management adalah cara mengatur penggunaan internet agar perangkat atau aplikasi penting mendapat prioritas. Tujuannya bukan membuat koneksi menjadi lebih cepat dari paket, tetapi membuat pembagian lebih adil dan pengalaman lebih stabil.',
                    'Fitur QoS pada router dapat membantu memprioritaskan video conference, VoIP, game online, atau perangkat kerja. Beberapa router modern menyediakan mode sederhana seperti gaming, streaming, atau work from home yang mudah dipakai pengguna rumahan.',
                    'Untuk rumah ramai, pisahkan perangkat penting dan perangkat hiburan. Laptop kerja dan perangkat belajar online bisa mendapat prioritas lebih tinggi, sementara smart TV atau konsol game bisa dibatasi ketika jam kerja atau jam sekolah.',
                    'Upload sering menjadi penyebab meeting patah-patah. Ketika satu perangkat mengunggah file besar ke cloud, video call bisa terganggu meski download masih terlihat cukup. Karena itu, pembatasan upload sama pentingnya dengan pembatasan download.',
                    'Gunakan kabel LAN untuk perangkat tetap seperti PC kerja, smart TV, atau konsol. Jalur kabel lebih stabil dan mengurangi beban Wi-Fi. Untuk perangkat mobile, pastikan berada di frekuensi yang tepat dan tidak terlalu jauh dari router.',
                    'Jika router bawaan tidak memiliki fitur manajemen bandwidth yang memadai, pertimbangkan router tambahan yang mendukung QoS lebih baik. Untuk rumah yang sangat ramai, perangkat jaringan yang tepat bisa memberi peningkatan besar dibanding hanya upgrade paket.',
                    'Manajemen bandwidth membuat internet lebih nyaman dipakai bersama. Dengan prioritas yang benar, meeting tetap lancar, streaming tetap jalan, dan pengguna lain tidak saling berebut koneksi tanpa kendali.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Bandwidth Management Rumah agar Meeting Stabil',
                'meta_description' => 'Cara mengatur bandwidth rumah ramai dengan QoS, prioritas perangkat, batas upload, kabel LAN, dan router yang tepat.',
                'published_at' => now()->setTime(14, 10),
            ],
            [
                'title' => 'Perawatan Jaringan Fiber di Musim Hujan: Tips Mencegah Gangguan Internet',
                'excerpt' => 'Musim hujan bisa memicu gangguan fisik jaringan. Simak tips menjaga perangkat, kabel, konektor, dan instalasi fiber tetap aman.',
                'body' => $this->article([
                    'Jaringan fiber optik relatif tahan terhadap gangguan elektromagnetik dan cuaca, tetapi instalasi fisik tetap bisa terdampak musim hujan. Angin kencang, pohon tumbang, rembesan air, dan pekerjaan lingkungan dapat memengaruhi kabel, ODP, atau perangkat pelanggan.',
                    'Di sisi pelanggan, pastikan ONT dan router berada di tempat kering, tidak menempel langsung pada lantai, dan jauh dari area rawan bocor. Perangkat jaringan bekerja 24 jam, sehingga kelembapan dan panas berlebih dapat memperpendek umur perangkat.',
                    'Gunakan stop kontak yang baik dan hindari sambungan listrik bertumpuk. Saat hujan disertai petir, risiko lonjakan listrik meningkat. UPS kecil atau stabilizer berkualitas dapat membantu menjaga perangkat tetap aman, terutama untuk pelanggan bisnis.',
                    'Jangan menekuk kabel fiber terlalu tajam. Kabel fiber memang kecil, tetapi sensitif terhadap tekukan ekstrem. Jika kabel tertarik, terjepit pintu, atau tergulung terlalu rapat, sinyal optik bisa melemah dan koneksi menjadi tidak stabil.',
                    'Perhatikan jalur kabel di luar rumah. Jika ada kabel terlihat turun, tertarik ranting, atau menggantung rendah, segera laporkan ke provider. Jangan mencoba menyambung atau menarik kabel fiber sendiri karena bisa memperburuk kerusakan.',
                    'Untuk ISP, musim hujan adalah waktu penting untuk inspeksi ODP, penguatan tiang, perapian slack kabel, dan pengecekan jalur rawan pohon. Dokumentasi jaringan yang rapi mempercepat tim lapangan menemukan titik gangguan.',
                    'Pelanggan juga bisa membantu dengan memberikan informasi lokasi gangguan yang jelas. Foto kondisi kabel, patokan rumah, dan status lampu ONT akan mempercepat diagnosis awal.',
                    'Perawatan sederhana sebelum dan selama musim hujan dapat mencegah banyak gangguan. Internet stabil bukan hanya soal perangkat canggih, tetapi juga instalasi fisik yang aman dan respons cepat saat ada risiko lapangan.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1519692933481-e162a57d6721?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Perawatan Jaringan Fiber Saat Musim Hujan',
                'meta_description' => 'Tips mencegah gangguan internet fiber di musim hujan: lindungi ONT, router, kabel, listrik, konektor, dan jalur luar rumah.',
                'published_at' => now()->setTime(15, 5),
            ],
            [
                'title' => 'Keamanan Router 2026: Kebiasaan Wajib agar Jaringan Rumah Tidak Mudah Disusupi',
                'excerpt' => 'Router adalah pintu utama jaringan rumah. Pelajari kebiasaan keamanan router: update firmware, password admin, guest network, dan audit perangkat.',
                'body' => $this->article([
                    'Router adalah gerbang utama semua perangkat rumah ke internet. Jika router tidak aman, seluruh jaringan bisa terdampak. Karena jumlah perangkat smart home terus bertambah, keamanan router menjadi kebiasaan wajib, bukan hanya urusan teknisi.',
                    'Ganti password admin router segera setelah pemasangan. Banyak pengguna mengganti password Wi-Fi, tetapi membiarkan password admin tetap bawaan. Ini berbahaya karena siapa pun yang tersambung ke jaringan bisa mencoba mengubah pengaturan router.',
                    'Gunakan password Wi-Fi yang kuat dan jangan membagikannya sembarangan. Untuk tamu, aktifkan guest network agar perangkat pengunjung tidak berada di jaringan yang sama dengan laptop kerja, CCTV, printer, atau penyimpanan lokal.',
                    'Update firmware router jika vendor menyediakan pembaruan. Firmware baru biasanya membawa perbaikan keamanan, stabilitas, dan kompatibilitas. Router yang tidak pernah diperbarui lebih rentan terhadap celah lama.',
                    'Matikan fitur yang tidak dipakai seperti WPS, remote management, atau UPnP jika tidak diperlukan. Fitur-fitur ini memang memudahkan, tetapi juga bisa memperbesar permukaan risiko jika tidak dikelola dengan benar.',
                    'Audit daftar perangkat secara berkala. Jika ada perangkat tidak dikenal, ubah password Wi-Fi dan restart router. Beri nama perangkat utama agar lebih mudah membedakan ponsel keluarga, smart TV, CCTV, dan perangkat tamu.',
                    'Pisahkan perangkat IoT jika router mendukung VLAN atau jaringan terpisah. Perangkat murah seperti kamera, lampu pintar, atau sensor kadang jarang mendapat update keamanan, sehingga lebih aman jika tidak bercampur dengan perangkat kerja.',
                    'Keamanan router tidak harus rumit. Dengan password kuat, firmware terbaru, guest network, audit perangkat, dan fitur yang dikurangi seperlunya, jaringan rumah menjadi jauh lebih aman untuk penggunaan harian.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
                'category' => 'tips',
                'meta_title' => 'Keamanan Router 2026 agar Wi-Fi Tidak Disusupi',
                'meta_description' => 'Panduan keamanan router 2026: password admin, update firmware, guest network, matikan WPS, audit perangkat, dan pisahkan IoT.',
                'published_at' => now()->setTime(16, 0),
            ],
            [
                'title' => 'Edge Computing untuk ISP Lokal: Kenapa Server Lebih Dekat Membuat Internet Terasa Cepat',
                'excerpt' => 'Edge computing membantu mengurangi latency dengan mendekatkan layanan ke pengguna. Pahami manfaatnya untuk ISP lokal, gaming, streaming, dan bisnis.',
                'body' => $this->article([
                    'Edge computing adalah pendekatan menempatkan proses komputasi atau konten lebih dekat dengan pengguna. Dalam konteks internet, server yang lebih dekat dapat mengurangi latency, mempercepat akses, dan mengurangi beban jalur utama ke internet global.',
                    'Bagi pengguna, manfaat edge computing terasa pada aplikasi yang membutuhkan respons cepat. Game online, streaming, video conference, aplikasi kasir cloud, dan layanan berbasis AI dapat berjalan lebih nyaman ketika data tidak harus menempuh rute terlalu jauh.',
                    'Untuk ISP lokal, konsep edge bisa hadir dalam bentuk cache konten, peering lokal, DNS yang optimal, atau server layanan internal. Semakin banyak trafik populer dilayani dari lokasi dekat pelanggan, semakin efisien kapasitas jaringan.',
                    'Peering menjadi bagian penting. Ketika ISP memiliki interkoneksi yang baik ke jaringan lain atau pusat pertukaran internet, rute data bisa lebih pendek. Dampaknya bukan hanya kecepatan download, tetapi juga ping lebih stabil.',
                    'Edge computing juga relevan untuk CCTV cloud, IoT, dan aplikasi bisnis lokal. Data yang diproses dekat lokasi pengguna dapat mengurangi delay dan membantu layanan tetap responsif saat trafik internet luas sedang padat.',
                    'Namun edge bukan solusi instan untuk semua masalah. Jaringan akses tetap harus baik, fiber harus rapi, router pelanggan harus sesuai, dan monitoring kapasitas tetap dibutuhkan. Server dekat tidak akan membantu jika Wi-Fi rumah bermasalah atau jalur distribusi overload.',
                    'Strategi edge perlu disesuaikan dengan skala ISP. Langkah awal bisa dimulai dari DNS yang baik, pemilihan upstream berkualitas, peering, dan monitoring trafik populer. Investasi lebih besar dapat dilakukan ketika pola trafik sudah jelas.',
                    'Masa depan internet lokal bukan hanya paket lebih besar, tetapi rute lebih efisien dan layanan lebih dekat dengan pengguna. Edge computing membantu membuat internet terasa cepat, bukan hanya terlihat cepat di angka promosi.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
                'category' => 'umum',
                'meta_title' => 'Edge Computing untuk ISP Lokal dan Internet Cepat',
                'meta_description' => 'Kenali edge computing untuk ISP lokal: server lebih dekat, latency rendah, peering, cache konten, gaming, streaming, dan bisnis.',
                'published_at' => now()->setTime(17, 0),
            ],
            [
                'title' => 'Pengumuman: Tim-7 Net Akan Menerapkan Sistem Isolir untuk Seluruh Pelanggan',
                'excerpt' => 'Tim-7 Net akan menerapkan sistem isolir layanan internet untuk seluruh pelanggan sebagai bagian dari peningkatan ketertiban administrasi, stabilitas layanan, dan transparansi pembayaran.',
                'body' => $this->article([
                    'Kepada seluruh pelanggan Tim-7 Net, kami informasikan bahwa Tim-7 Net akan menerapkan sistem isolir layanan internet secara bertahap untuk seluruh pelanggan. Kebijakan ini dilakukan sebagai bagian dari peningkatan tata kelola layanan, ketertiban administrasi pembayaran, dan menjaga kualitas jaringan agar tetap stabil bagi semua pengguna.',
                    'Sistem isolir adalah pembatasan akses layanan internet sementara kepada pelanggan yang belum menyelesaikan kewajiban pembayaran sesuai jatuh tempo yang berlaku. Saat layanan berada dalam status isolir, koneksi internet pelanggan akan dibatasi atau tidak dapat digunakan sampai tagihan diselesaikan.',
                    'Penerapan sistem isolir bukan bertujuan mempersulit pelanggan, melainkan memastikan layanan berjalan lebih tertib, adil, dan berkelanjutan. Dengan pembayaran yang lebih teratur, Tim-7 Net dapat menjaga operasional jaringan, melakukan perawatan perangkat, meningkatkan kapasitas, dan memberikan dukungan teknis yang lebih baik.',
                    'Pelanggan diimbau untuk selalu memperhatikan tanggal jatuh tempo tagihan. Informasi tagihan dapat dicek melalui kanal resmi Tim-7 Net atau menghubungi admin layanan pelanggan. Jika pembayaran sudah dilakukan tetapi layanan masih berstatus isolir, pelanggan dapat mengirimkan bukti pembayaran agar proses pengecekan dan aktivasi ulang dapat dilakukan lebih cepat.',
                    'Setelah pembayaran dikonfirmasi, layanan internet akan dibuka kembali sesuai prosedur sistem. Pada kondisi normal, proses pembukaan isolir dapat berjalan otomatis atau diproses oleh admin setelah data pembayaran tervalidasi. Pastikan nama pelanggan, nomor layanan, dan bukti pembayaran dikirim dengan jelas untuk menghindari keterlambatan verifikasi.',
                    'Tim-7 Net juga mengimbau pelanggan untuk menggunakan metode pembayaran resmi dan menghindari pembayaran ke pihak yang tidak berwenang. Simpan bukti pembayaran sampai status tagihan dinyatakan lunas. Langkah ini penting agar riwayat administrasi pelanggan tetap aman dan mudah ditelusuri.',
                    'Bagi pelanggan yang memiliki kendala pembayaran, pindah lokasi, perubahan paket, atau pertanyaan terkait status layanan, silakan menghubungi tim admin Tim-7 Net melalui kontak resmi. Kami akan membantu memberikan informasi sesuai data pelanggan dan ketentuan layanan yang berlaku.',
                    'Kami mengucapkan terima kasih atas pengertian dan kerja sama seluruh pelanggan. Dengan penerapan sistem isolir yang tertib dan transparan, Tim-7 Net berharap kualitas layanan internet dapat terus meningkat, jaringan lebih stabil, dan pengalaman pelanggan menjadi lebih baik.',
                ]),
                'cover_image' => 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80',
                'category' => 'pengumuman',
                'meta_title' => 'Pengumuman Sistem Isolir Pelanggan Tim-7 Net',
                'meta_description' => 'Tim-7 Net akan menerapkan sistem isolir untuk seluruh pelanggan demi ketertiban pembayaran, transparansi administrasi, dan kualitas layanan.',
                'published_at' => now()->setTime(18, 0),
            ],
        ];

        foreach ($articles as $article) {
            $slug = Str::slug($article['title']);

            News::updateOrCreate(
                ['slug' => $slug],
                [
                    'title' => $article['title'],
                    'excerpt' => $article['excerpt'],
                    'body' => $article['body'],
                    'cover_image' => $article['cover_image'],
                    'author' => 'Tim-7 Net',
                    'category' => $article['category'],
                    'status' => 'published',
                    'published_at' => $article['published_at'],
                    'meta_title' => $article['meta_title'],
                    'meta_description' => $article['meta_description'],
                    'view_count' => 0,
                ]
            );
        }
    }

    /**
     * Convert paragraph arrays to the plain-text format used by the news view.
     *
     * @param  array<int, string>  $paragraphs
     */
    private function article(array $paragraphs): string
    {
        return implode("\n\n", $paragraphs);
    }
}
